/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Menu_Editar.Frm_infoalerta;
import Menu_Editar.Frm_buscar;
import Menu_Editar.Frm_reemplazar;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;

/**
 *
 * @author Cristian Padilla
 */
public class Frm_iniciar extends javax.swing.JFrame {

    public static boolean creoNuevo = false;
    public static boolean abrioArchivo = false;
    public static String valor;
    
    public Frm_iniciar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_background = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_salida = new javax.swing.JTextArea();
        lbl_palaImpar = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_totalpalabras = new javax.swing.JLabel();
        lbl_primerale = new javax.swing.JLabel();
        lbl_ultimale = new javax.swing.JLabel();
        lbl_letracentral = new javax.swing.JLabel();
        lbl_repeticionesA = new javax.swing.JLabel();
        lbl_repeticionesE = new javax.swing.JLabel();
        lbl_repeticionesI = new javax.swing.JLabel();
        lbl_repeticionesO = new javax.swing.JLabel();
        lbl_repeticionesU = new javax.swing.JLabel();
        lbl_primerapa = new javax.swing.JLabel();
        lbl_palacentral = new javax.swing.JLabel();
        lbl_ultimapa = new javax.swing.JLabel();
        lbl_palaPar = new javax.swing.JLabel();
        lbl_longitudtxt1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_entrada = new javax.swing.JTextArea();
        btb_procesar = new javax.swing.JButton();
        lbl_letra_central = new javax.swing.JLabel();
        lbl_longitud = new javax.swing.JLabel();
        lbl_total_palabras = new javax.swing.JLabel();
        lbl_primer_letra = new javax.swing.JLabel();
        lbl_ultima_letra = new javax.swing.JLabel();
        lbl_rep_A = new javax.swing.JLabel();
        lbl_rep_E = new javax.swing.JLabel();
        lbl_rep_I = new javax.swing.JLabel();
        lbl_rep_O = new javax.swing.JLabel();
        lbl_rep_U = new javax.swing.JLabel();
        lbl_primera_palabra = new javax.swing.JLabel();
        lbl_palabra_central = new javax.swing.JLabel();
        lbl_ultima_palabra = new javax.swing.JLabel();
        lbl_cantidad_par = new javax.swing.JLabel();
        lbl_cantidad_impar = new javax.swing.JLabel();
        mb_menubar = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jm_guardar = new javax.swing.JMenuItem();
        jm_saveas = new javax.swing.JMenuItem();
        jm_editar = new javax.swing.JMenu();
        jm_copiar = new javax.swing.JMenuItem();
        jm_cortar = new javax.swing.JMenuItem();
        jm_pegar = new javax.swing.JMenuItem();
        jm_buscar = new javax.swing.JMenuItem();
        jm_remplazar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_background.setBackground(new java.awt.Color(19, 75, 112));
        pn_background.setForeground(new java.awt.Color(204, 204, 204));
        pn_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logo.setFont(new java.awt.Font("Fira Code", 1, 24)); // NOI18N
        lbl_logo.setForeground(new java.awt.Color(238, 238, 238));
        lbl_logo.setText("Traductor Murciélago");
        pn_background.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 300, 40));

        txt_salida.setBackground(new java.awt.Color(32, 30, 67));
        txt_salida.setColumns(20);
        txt_salida.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        txt_salida.setForeground(new java.awt.Color(238, 238, 238));
        txt_salida.setRows(5);
        txt_salida.setText("TRADUCCION A CODIGO MURCIELAGO");
        txt_salida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jScrollPane1.setViewportView(txt_salida);

        pn_background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 880, 160));

        lbl_palaImpar.setForeground(new java.awt.Color(238, 238, 238));
        lbl_palaImpar.setText("Palabras con cantida de caracter impar:");
        pn_background.add(lbl_palaImpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        lbl_nombre.setForeground(new java.awt.Color(238, 238, 238));
        pn_background.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 110, 20));

        lbl_totalpalabras.setForeground(new java.awt.Color(238, 238, 238));
        lbl_totalpalabras.setText("Total de palabras:");
        pn_background.add(lbl_totalpalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        lbl_primerale.setForeground(new java.awt.Color(238, 238, 238));
        lbl_primerale.setText("Primer letra del texto:");
        pn_background.add(lbl_primerale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        lbl_ultimale.setForeground(new java.awt.Color(238, 238, 238));
        lbl_ultimale.setText("Ultima letra del texto:");
        pn_background.add(lbl_ultimale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        lbl_letracentral.setForeground(new java.awt.Color(238, 238, 238));
        lbl_letracentral.setText("Letra central del texto: ");
        pn_background.add(lbl_letracentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        lbl_repeticionesA.setForeground(new java.awt.Color(238, 238, 238));
        lbl_repeticionesA.setText("Repeticiones de \"A\", \"a\" y \"á\":");
        pn_background.add(lbl_repeticionesA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        lbl_repeticionesE.setForeground(new java.awt.Color(238, 238, 238));
        lbl_repeticionesE.setText("Repeticiones de \"E\",\"e\" y \"é\":");
        pn_background.add(lbl_repeticionesE, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        lbl_repeticionesI.setForeground(new java.awt.Color(238, 238, 238));
        lbl_repeticionesI.setText("Repeticions de \"I\",\"i\" y \"í\":");
        pn_background.add(lbl_repeticionesI, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        lbl_repeticionesO.setForeground(new java.awt.Color(238, 238, 238));
        lbl_repeticionesO.setText("Repeticiones de \"O\",\"o\" y \"ó\":");
        pn_background.add(lbl_repeticionesO, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        lbl_repeticionesU.setForeground(new java.awt.Color(238, 238, 238));
        lbl_repeticionesU.setText("Repeticiones de \"U\",\"u\" y \"ú\":");
        pn_background.add(lbl_repeticionesU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        lbl_primerapa.setForeground(new java.awt.Color(238, 238, 238));
        lbl_primerapa.setText("Primera palabra:");
        pn_background.add(lbl_primerapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        lbl_palacentral.setForeground(new java.awt.Color(238, 238, 238));
        lbl_palacentral.setText("Palabra central:");
        pn_background.add(lbl_palacentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        lbl_ultimapa.setForeground(new java.awt.Color(238, 238, 238));
        lbl_ultimapa.setText("Ultima palabra: ");
        pn_background.add(lbl_ultimapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        lbl_palaPar.setForeground(new java.awt.Color(238, 238, 238));
        lbl_palaPar.setText("Palabras con cantidad de caracter par:");
        lbl_palaPar.setFocusable(false);
        pn_background.add(lbl_palaPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 220, -1));

        lbl_longitudtxt1.setForeground(new java.awt.Color(238, 238, 238));
        lbl_longitudtxt1.setText("Longitud del texto: ");
        pn_background.add(lbl_longitudtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        txt_entrada.setBackground(new java.awt.Color(32, 30, 67));
        txt_entrada.setColumns(20);
        txt_entrada.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        txt_entrada.setForeground(new java.awt.Color(238, 238, 238));
        txt_entrada.setRows(5);
        txt_entrada.setText("Ingrese un texto o abra un archivo");
        txt_entrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        txt_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_entradaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txt_entrada);

        pn_background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 880, 160));

        btb_procesar.setBackground(new java.awt.Color(80, 140, 155));
        btb_procesar.setFont(new java.awt.Font("Fira Code", 1, 12)); // NOI18N
        btb_procesar.setForeground(new java.awt.Color(238, 238, 238));
        btb_procesar.setText("Procesar");
        btb_procesar.setBorder(null);
        btb_procesar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btb_procesarMouseClicked(evt);
            }
        });
        btb_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_procesarActionPerformed(evt);
            }
        });
        pn_background.add(btb_procesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 90, 40));

        lbl_letra_central.setForeground(new java.awt.Color(238, 238, 238));
        lbl_letra_central.setText("0");
        pn_background.add(lbl_letra_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 30, -1));

        lbl_longitud.setForeground(new java.awt.Color(238, 238, 238));
        lbl_longitud.setText("0");
        pn_background.add(lbl_longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 30, -1));

        lbl_total_palabras.setForeground(new java.awt.Color(238, 238, 238));
        lbl_total_palabras.setText("0");
        pn_background.add(lbl_total_palabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 30, -1));

        lbl_primer_letra.setForeground(new java.awt.Color(238, 238, 238));
        lbl_primer_letra.setText("0");
        pn_background.add(lbl_primer_letra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 30, -1));

        lbl_ultima_letra.setForeground(new java.awt.Color(238, 238, 238));
        lbl_ultima_letra.setText("0");
        pn_background.add(lbl_ultima_letra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 30, -1));

        lbl_rep_A.setForeground(new java.awt.Color(238, 238, 238));
        lbl_rep_A.setText("0");
        pn_background.add(lbl_rep_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 30, -1));

        lbl_rep_E.setForeground(new java.awt.Color(238, 238, 238));
        lbl_rep_E.setText("0");
        pn_background.add(lbl_rep_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 30, -1));

        lbl_rep_I.setForeground(new java.awt.Color(238, 238, 238));
        lbl_rep_I.setText("0");
        pn_background.add(lbl_rep_I, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 30, -1));

        lbl_rep_O.setForeground(new java.awt.Color(238, 238, 238));
        lbl_rep_O.setText("0");
        pn_background.add(lbl_rep_O, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 30, -1));

        lbl_rep_U.setForeground(new java.awt.Color(238, 238, 238));
        lbl_rep_U.setText("0");
        pn_background.add(lbl_rep_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 30, -1));

        lbl_primera_palabra.setForeground(new java.awt.Color(238, 238, 238));
        lbl_primera_palabra.setText("0");
        pn_background.add(lbl_primera_palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 260, -1));

        lbl_palabra_central.setForeground(new java.awt.Color(238, 238, 238));
        lbl_palabra_central.setText("0");
        pn_background.add(lbl_palabra_central, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 260, -1));

        lbl_ultima_palabra.setForeground(new java.awt.Color(238, 238, 238));
        lbl_ultima_palabra.setText("0");
        pn_background.add(lbl_ultima_palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 260, -1));

        lbl_cantidad_par.setForeground(new java.awt.Color(238, 238, 238));
        lbl_cantidad_par.setText("0");
        pn_background.add(lbl_cantidad_par, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 30, -1));

        lbl_cantidad_impar.setForeground(new java.awt.Color(238, 238, 238));
        lbl_cantidad_impar.setText("0");
        pn_background.add(lbl_cantidad_impar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 50, -1));

        mb_menubar.setBackground(new java.awt.Color(80, 140, 155));
        mb_menubar.setBorder(null);
        mb_menubar.setForeground(new java.awt.Color(255, 255, 255));
        mb_menubar.setBorderPainted(false);

        jm_archivo.setBackground(new java.awt.Color(80, 140, 155));
        jm_archivo.setForeground(new java.awt.Color(238, 238, 238));
        jm_archivo.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_archivo.add(jMenuItem1);

        jm_guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_guardar.setText("Guardar");
        jm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_guardar);

        jm_saveas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jm_saveas.setText("Guardar como");
        jm_saveas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_saveasActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_saveas);

        mb_menubar.add(jm_archivo);

        jm_editar.setBackground(new java.awt.Color(80, 140, 155));
        jm_editar.setBorder(null);
        jm_editar.setForeground(new java.awt.Color(238, 238, 238));
        jm_editar.setText("Editar");

        jm_copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_copiar.setText("Copiar");
        jm_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_copiarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_copiar);

        jm_cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_cortar.setText("Cortar");
        jm_cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_cortarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_cortar);

        jm_pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_pegar.setText("Pegar");
        jm_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_pegarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_pegar);

        jm_buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_buscar.setText("Buscar");
        jm_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_buscarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_buscar);

        jm_remplazar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jm_remplazar.setText("Reemplazar");
        jm_remplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_remplazarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_remplazar);

        mb_menubar.add(jm_editar);

        setJMenuBar(mb_menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_background, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_background, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Archivo().LeerFichero(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarActionPerformed

        if (abrioArchivo) {
            System.out.println("Existente");
            new Archivo().GuardarFichero(Frm_iniciar.txt_entrada.getText(), Frm_iniciar.lbl_nombre.getText());
        }
        if (creoNuevo) {
            System.out.println("Nuevo");
            new Archivo().CrearFicheroNuevo(this, Frm_iniciar.txt_entrada.getText(), Frm_iniciar.lbl_nombre.getText());
        }
        if (!creoNuevo && !abrioArchivo) {
            Menu_Editar.Frm_infoalerta a = new Frm_infoalerta(this, true);
            Frm_infoalerta.lbl_mensaje1.setText("Debes abrir un archivo para poder guardarlo.");
            a.setVisible(true);
        }
    }//GEN-LAST:event_jm_guardarActionPerformed

    private void jm_saveasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_saveasActionPerformed
        if (abrioArchivo) {
            System.out.println("Existente");
            new Archivo().GuardarFichero(Frm_iniciar.txt_entrada.getText(), Frm_iniciar.lbl_nombre.getText());
        }
        if (creoNuevo) {
            System.out.println("Nuevo");
            new Archivo().CrearFicheroNuevo(this, Frm_iniciar.txt_entrada.getText(), Frm_iniciar.lbl_nombre.getText());
        }
        if (!creoNuevo && !abrioArchivo) {
            Menu_Editar.Frm_infoalerta a = new Frm_infoalerta(this, true);
            Frm_infoalerta.lbl_mensaje1.setText("Debes abrir un archivo para poder guardarlo.");
            a.setVisible(true);
        }
    }//GEN-LAST:event_jm_saveasActionPerformed

    private void txt_entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_entradaMouseClicked
        if ("Ingrese un texto o abra un archivo".equals(txt_entrada.getText())){
            txt_entrada.setText("");
            txt_entrada.setForeground(Color.white);}
    }//GEN-LAST:event_txt_entradaMouseClicked

    private void btb_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_procesarActionPerformed
        
    }//GEN-LAST:event_btb_procesarActionPerformed

    private void jm_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_copiarActionPerformed
        StringSelection selection = new StringSelection(txt_entrada.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);        
    }//GEN-LAST:event_jm_copiarActionPerformed

    private void jm_cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_cortarActionPerformed
        StringSelection selection = new StringSelection(txt_entrada.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);  
        txt_entrada.setText("");
    }//GEN-LAST:event_jm_cortarActionPerformed

    private void jm_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_pegarActionPerformed
    
    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    DataFlavor flavor = DataFlavor.stringFlavor;
    if (clipboard.isDataFlavorAvailable(flavor)) {
      try {
        String text = (String) clipboard.getData(flavor);
        txt_entrada.setText(text);
      } catch (UnsupportedFlavorException | IOException e) {
        System.out.println(e);
      }
    }
    }//GEN-LAST:event_jm_pegarActionPerformed

    private void btb_procesarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btb_procesarMouseClicked
        //procesado 
        valor = txt_entrada.getText();
        String[] valorarray = txt_entrada.getText().split(" ");
        String[] chararray = valor.split("");
        int tamano1= 0;
        int tamano2=0;
        for (String valorarray1 : valorarray) {
            lbl_primera_palabra.setText(valorarray[0]);
            break;
        }
        
        for (String chararray1 : chararray) {
            tamano1 ++;
        }
        lbl_longitud.setText(Integer.toString(tamano1));
        
        for (String valorarray1 : valorarray) {
            tamano2 ++;
        }
        lbl_total_palabras.setText(Integer.toString(tamano2));
        
        for (String chararray1 : chararray) {
            lbl_primer_letra.setText(chararray[0]);
            break;
        }
           
        lbl_ultima_letra.setText(chararray[tamano1-1]);
        
        int medio1=tamano1/2;
        lbl_letra_central.setText(chararray[medio1]);
        
        int medio2=tamano2/2;
        lbl_palabra_central.setText(valorarray[medio2]);
        
        lbl_ultima_palabra.setText(valorarray[tamano2-1]);
        
        Funciones.Repa(valor,"a");
       
        Funciones.Repe(valor,"e");

        Funciones.Repi(valor,"i");

        Funciones.Repo(valor,"o");

        Funciones.Repu(valor,"u");
        
        Funciones.PAR(valor);
        
        Codificar.Encode(valor);
        
    }//GEN-LAST:event_btb_procesarMouseClicked

    private void jm_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_buscarActionPerformed

        Menu_Editar.Frm_buscar a = new Frm_buscar(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_jm_buscarActionPerformed

    private void jm_remplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_remplazarActionPerformed

        Menu_Editar.Frm_reemplazar a = new Frm_reemplazar(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_jm_remplazarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frm_iniciar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_procesar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenuItem jm_buscar;
    private javax.swing.JMenuItem jm_copiar;
    private javax.swing.JMenuItem jm_cortar;
    private javax.swing.JMenu jm_editar;
    private javax.swing.JMenuItem jm_guardar;
    private javax.swing.JMenuItem jm_pegar;
    private javax.swing.JMenuItem jm_remplazar;
    private javax.swing.JMenuItem jm_saveas;
    public static javax.swing.JLabel lbl_cantidad_impar;
    public static javax.swing.JLabel lbl_cantidad_par;
    private javax.swing.JLabel lbl_letra_central;
    private javax.swing.JLabel lbl_letracentral;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_longitud;
    private javax.swing.JLabel lbl_longitudtxt1;
    public static javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_palaImpar;
    private javax.swing.JLabel lbl_palaPar;
    private javax.swing.JLabel lbl_palabra_central;
    private javax.swing.JLabel lbl_palacentral;
    private javax.swing.JLabel lbl_primer_letra;
    private javax.swing.JLabel lbl_primera_palabra;
    private javax.swing.JLabel lbl_primerale;
    private javax.swing.JLabel lbl_primerapa;
    public static javax.swing.JLabel lbl_rep_A;
    public static javax.swing.JLabel lbl_rep_E;
    public static javax.swing.JLabel lbl_rep_I;
    public static javax.swing.JLabel lbl_rep_O;
    public static javax.swing.JLabel lbl_rep_U;
    private javax.swing.JLabel lbl_repeticionesA;
    private javax.swing.JLabel lbl_repeticionesE;
    private javax.swing.JLabel lbl_repeticionesI;
    private javax.swing.JLabel lbl_repeticionesO;
    private javax.swing.JLabel lbl_repeticionesU;
    private javax.swing.JLabel lbl_total_palabras;
    private javax.swing.JLabel lbl_totalpalabras;
    private javax.swing.JLabel lbl_ultima_letra;
    private javax.swing.JLabel lbl_ultima_palabra;
    private javax.swing.JLabel lbl_ultimale;
    private javax.swing.JLabel lbl_ultimapa;
    private javax.swing.JMenuBar mb_menubar;
    private javax.swing.JPanel pn_background;
    public static javax.swing.JTextArea txt_entrada;
    public static javax.swing.JTextArea txt_salida;
    // End of variables declaration//GEN-END:variables
}
